---
- hosts:  webserver

  vars:
    exec_dir:  /tmp

  vars_prompt:
    - name: "fw_action"
      prompt:  "Enable or disable webserver access, 'enable' or 'disable':"
      private: no
      default: enable

  tasks:
  - name:  copy firewal scritps to hosts
    become: true
    copy:
      src={{ item }}
      dest={{ exec_dir }}
    with_items:
      - scripts/open_firewall_22_80_only.sh
      - scripts/open_firewall_22_only.sh

  - name: Enable access to the website
    become: true
    command: "{{ item }}"
    with_items:
      - "chmod 755 {{ exec_dir }}/open_firewall_22_80_only.sh"
      - "{{ exec_dir }}/open_firewall_22_80_only.sh"
    when: fw_action == "enable"

  - name: Disable access to the website
    become: true
    command: "{{ item }}"
    with_items:
      - "chmod 755 {{ exec_dir }}/open_firewall_22_only.sh"
      - "{{ exec_dir }}/open_firewall_22_only.sh"
    when: fw_action == "disable"
